CREATE TABLE IF NOT EXISTS hits
(
    id        BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    app       VARCHAR(255) NOT NULL,
    uri       TEXT         NOT NULL,
    ip        VARCHAR(45)  NOT NULL,
    timestamp TIMESTAMP    NOT NULL
);

-- CREATE INDEX idx_hits_stats_app ON hits_stats (app);
-- CREATE INDEX idx_hits_stats_timestamp ON hits_stats (timestamp);
-- CREATE INDEX idx_hits_stats_app_timestamp ON hits_stats (app, timestamp);